### ISSUE TITLE
ImportDatabase can't actually handle if the psv does not exist

### ISSUE THREAD

**Issue by thespacepanda** [bmuk/PipeDB#4]
This is apparently because the using statement will throw an exception before the File.Exists code even gets run. I'm not sure how to resolve this (other than calling file exists outside the using statement; I really just don't know the best practices for something like this) so I'm assigning it to you.

**Comment by jester155** [comment]
Can you give me the line number and .cs file in question?

**Comment by thespacepanda** [comment]
This is fixed, any other issues related to this will be fixed when I upgrade to using FileStreams
